name: Deploy to AWS S3

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v5

    - name: Build Flutter app
      run: flutter build web

    - name: Upload to AWS S3
      uses: jakejarvis/s3-sync-action@v0.2.4
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SRC: build/web/
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: './'